// <auto-generated />
using EntityFramework.V70.Relationships.OneToOneRequired;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations.OneToOneRequired.BC1
{
    [DbContext(typeof(BlogContext1))]
    [Migration("20231006073516_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneRequired.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneRequired.BlogHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlogId")
                        .IsUnique();

                    b.ToTable("BlogHeaders");
                });

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneRequired.BlogHeader", b =>
                {
                    b.HasOne("EntityFramework.V70.Relationships.OneToOneRequired.Blog", "Blog")
                        .WithOne("Header")
                        .HasForeignKey("EntityFramework.V70.Relationships.OneToOneRequired.BlogHeader", "BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneRequired.Blog", b =>
                {
                    b.Navigation("Header");
                });
#pragma warning restore 612, 618
        }
    }
}
