// <auto-generated />
using System;
using EntityFramework.V70.Relationships.OneToOneOptional;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations.OneToOneOptional.BC1
{
    [DbContext(typeof(BlogContext1))]
    partial class BlogContext1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneOptional.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneOptional.BlogHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlogId")
                        .IsUnique();

                    b.ToTable("BlogHeaders");
                });

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneOptional.BlogHeader", b =>
                {
                    b.HasOne("EntityFramework.V70.Relationships.OneToOneOptional.Blog", "Blog")
                        .WithOne("Header")
                        .HasForeignKey("EntityFramework.V70.Relationships.OneToOneOptional.BlogHeader", "BlogId");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EntityFramework.V70.Relationships.OneToOneOptional.Blog", b =>
                {
                    b.Navigation("Header");
                });
#pragma warning restore 612, 618
        }
    }
}
